// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwKaZCW3aCIYVLBpJ8kZEsnebBrfgE7hs',
    appId: '1:699522358842:web:ae0b46bcaa204511ce5f03',
    messagingSenderId: '699522358842',
    projectId: 'noteapp-a8a7d',
    authDomain: 'noteapp-a8a7d.firebaseapp.com',
    storageBucket: 'noteapp-a8a7d.appspot.com',
    measurementId: 'G-WR33DVDRVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4e1lksNWSiqJj8Ha2DHnYpNlbRsX49M',
    appId: '1:699522358842:android:160c65e5152fc84ece5f03',
    messagingSenderId: '699522358842',
    projectId: 'noteapp-a8a7d',
    storageBucket: 'noteapp-a8a7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsSTc_c1RqfaHfobX1wULIIB1hy9T36mw',
    appId: '1:699522358842:ios:1dc1b49270657331ce5f03',
    messagingSenderId: '699522358842',
    projectId: 'noteapp-a8a7d',
    storageBucket: 'noteapp-a8a7d.appspot.com',
    iosClientId: '699522358842-m7d0rfi7v694tbpunaj334ihc3slt23v.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsSTc_c1RqfaHfobX1wULIIB1hy9T36mw',
    appId: '1:699522358842:ios:1dc1b49270657331ce5f03',
    messagingSenderId: '699522358842',
    projectId: 'noteapp-a8a7d',
    storageBucket: 'noteapp-a8a7d.appspot.com',
    iosClientId: '699522358842-m7d0rfi7v694tbpunaj334ihc3slt23v.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
